server:
  port: 9090

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/hit
    username: root
    password: JBuckets@13
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      password: JBuckets@13
  mvc:
    problemdetails:
      enabled: true
